[package]
name = "mc-sgx-dcap-quoteverify-sys-types"
version = "0.9.0"
authors = ["MobileCoin"]
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI type definitions used by the `sgx_dcap_quoteverify` library."
edition = "2021"
keywords = ["ffi", "sgx", "no-std"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[lib]
doctest = false

[dependencies]
mc-sgx-dcap-sys-types = { path = "../../../sys/types", version = "=0.9.0" }

[build-dependencies]
bindgen = "0.66.1"
cargo-emit = "0.2.1"
mc-sgx-core-build = { path = "../../../../core/build", version = "=0.9.0" }
