[package]
name = "test_enclave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cargo-emit = "0.2.1"
cc = "1.0.73"
bindgen = "0.59.2"
