[package]
name = "mc-sgx-dcap-quoteverify-types"
# When updating version, update the deps.rs link in README.md
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-dcap-quoteverify-sys-types = { path = "../sys/types", version = "=0.1.0" }
mc-sgx-core-types = { path = "../../../core/types", version = "=0.1.0" }

[dev-dependencies]
yare = "1.0.2"
