[package]
name = "mc-sgx-tstdc-sys"
version = "0.1.0"
authors = ["MobileCoin"]
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI bindings for `sgx_tstdc`."
edition = "2021"
keywords = ["ffi", "sgx", "no-std"]
license = "Apache-2.0"
links = "sgx_tstdc"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[lib]
# test false due to needing trts, and thus an enclave to fully link
test = false

[dependencies]
mc-sgx-tstdc-sys-types = { path = "types", version = "0.1.0" }
mc-sgx-core-sys-types = { path = "../../core/sys/types", version = "0.1.0" }

[build-dependencies]
bindgen = "0.60.1"
cargo-emit = "0.2.1"
mc-sgx-core-build = { path = "../../core/build", version = "0.1.0" }
