[package]
name = "mc-sgx-urts-sys-types"
version = "0.7.2"
authors = ["MobileCoin"]
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI types for `sgx_urts`."
edition = "2021"
keywords = ["ffi", "sgx", "no-std"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[lib]
doctest = false

[dependencies]
mc-sgx-core-sys-types = { path = "../../../core/sys/types", version = "=0.7.2" }

[build-dependencies]
bindgen = "0.66.1"
cargo-emit = "0.2.1"

mc-sgx-core-build = { path = "../../../core/build", version = "=0.7.2" }
