name: rust

on:
  pull_request:
    paths:
      - 'untrusted/**'
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

defaults:
  run:
    working-directory: "untrusted"

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: [self-hosted, Linux, small]
    container: mobilecoin/rust-sgx-base:latest
    steps:
      - uses: actions/checkout@v3
      # actions-rs/toolchain does not support the newer toml file format
      # see https://github.com/actions-rs/toolchain/issues/126
      - name: Setup rust toolchain
        run: rustup show
      - run: cargo build --release 
  test:
    runs-on: [self-hosted, Linux, small]
    container: mobilecoin/rust-sgx-base:latest
    steps:
      - uses: actions/checkout@v3
      # actions-rs/toolchain does not support the newer toml file format
      # see https://github.com/actions-rs/toolchain/issues/126
      - name: Setup rust toolchain
        run: rustup show
      - run: cargo test --release 
